name: Label Retrieval

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  retrieve-issue-labels:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract issue number
      id: extract-issue
      run: |
        branch_name=${{ github.event.pull_request.head.ref }}
        issue_number=$(echo "$branch_name" | grep -oP '^\d+')
        echo "::set-output name=issue_number::$issue_number"

    - name: Retrieve Issue Labels
      id: retrieve-issue-labels
      run: |
        issue_number=${{ steps.extract-issue.outputs.issue_number }}
        issue_data=$(curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$issue_number")
        issue_labels=$(echo "$issue_data" | jq -r '.labels[].name')
        echo "::set-output name=issue_labels::$issue_labels"

    - name: Apply Labels to Pull Request
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const prNumber = context.issue.number;
          const labels = `${{ steps.retrieve-issue-labels.outputs.issue_labels }}`.split('\n').filter(Boolean);
          await github.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            labels: labels
          });
