name: Label Retrieval

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  retrieve-labels:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Retrieve Labels
      run: |
        issue_number=$(jq --raw-output .pull_request.issue.number "$GITHUB_EVENT_PATH")
        labels=$(curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$issue_number" | jq -r '.labels | .[].name')

        echo "Labels: $labels"
