name: Get Label from issue
on: 
  pull_request:
    types: [opened, reopened]
    
jobs:
  display-github-context:
    runs-on: ubuntu-latest
    steps:
    - name: Get issue
      uses: actions-cool/issues-helper@v3
      id: getIssue
      with:
        actions: 'get-issue'
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: 3
        
    - name: Check Outputs
      run: echo "Outputs issue_labels is ${{ steps.getIssue.outputs.issue_labels }}"
