name: Github-Context
on: workflow_dispatch

jobs:
  display-github-context:
    runs-on: ubuntu-latest
    steps:
    - name: View the github context
      run: echo "$GITHUB_CONTEXT"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
