name: Increment semantic version
on:
  pull_request:
    types:
      - closed  
jobs:
  increment-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name: Get current version
        run: echo "current_version=$(git describe --tags --abbrev=0)"
        
      - name: Get labels
        run: |
          labels=$(echo "${{ github.event.pull_request.labels }}" | tr ',' ' ')
      - name: Increment version
        run: |
          match=$(echo $current_version | grep -E "^(\d+)\.(\d+)\.(\d+)$")
          if [[ $match ]]; then
            major=$(echo $match | cut -d. -f1)
            minor=$(echo $match | cut -d. -f2)
            patch=$(echo $match | cut -d. -f3)
            if [[ "enhancement" in $labels ]]; then
              minor=$((minor + 1))
              patch=0
            elif [[ "bug" in $labels ]]; then
              patch=$((patch + 1))
            else
              pass
            fi
            new_version="$major.$minor.$patch"
          else
            new_version=$current_version
          fi
          echo "new_version=$new_version"


