name: Increment semantic version
on:
  pull_request:
    types:
      - closed  
jobs:
  increment-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name: Get current version
        run: |
          echo "current_version=$(git describe --tags --abbrev=0)" >> "$GITHUB_ENV"
          IFS='.' read -r -a version_parts <<< "$version"
          major="${version_parts[0]}"
          minor="${version_parts[1]}"
          patch="${version_parts[2]}"
      
          if [[ contains(github.event.pull_request.labels.*.name, 'enhancement') ]]; then
              minor=$((minor + 1))
              patch=0
            elif [[ contains(github.event.pull_request.labels.*.name, 'bug')]]; then
              patch=$((patch + 1))
            else
              pass
            fi
            new_version="$major.$minor.$patch"
          else
            new_version=$current_version
          fi
          echo "new_version=$new_version"





      

            
            




