name: Increment semantic version
on:
  pull_request:
    types:
      - closed  
jobs:
  increment-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name: Get current version
        run: echo "current_version=$(git describe --tags --abbrev=0)" >> "$GITHUB_ENV"
      
      - name: Extract Label Names
        run: |
          # Install jq for JSON processing
          sudo apt-get update && sudo apt-get install -y jq

          # Extracting label names using jq and storing them in the 'label_names' variable
          label_names=$(echo "${{ toJson(github.event.pull_request.labels) }}" | jq -r '.[].name')

          # Printing the label names for verification
          echo "labels=$label_names" >> "$GITHUB_ENV"
      
      - name: Increment version
        run: |
          IFS='.' read -r -a version_parts <<< "$current_version"
          major="${version_parts[0]}"
          minor="${version_parts[1]}"
          patch="${version_parts[2]}"

          if [[ $env.labels, 'enhancement') ]]; then
            # Increment the minor version and set the patch to 0
            ((minor++))
            patch=0
          elif [[ $env.labels, 'bug')]]; then
            patch=$((patch + 1))
          else
            pass
          fi
          
            new_version="$major.$minor.$patch"
            
            




