name: Increment semantic version
on:
  pull_request:
    types:
      - closed  
jobs:
  increment-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name: Get current version
        run: |
          echo "current_version=$(git describe --tags --abbrev=0)"
          major=${current_version%%.*}
          minor=${current_version##*.}
          patch=${current_version##*.}
          echo "major=$major"
          echo "minor=$minor"
          echo "patch=$patch"
          echo "major=$major" >> "$GITHUB_ENV"
          echo "minor=$minor" >> "$GITHUB_ENV"
          echo "patch=$patch" >> "$GITHUB_ENV"
          





      

            
            




