name: Increment semantic version
on:
  pull_request:
    types:
      - closed  
jobs:
  increment-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name: Get current version
        run: echo "current_version=$(git describe --tags --abbrev=0)" >> "$GITHUB_ENV"
                  
      - name: Increment version
        run: |
          echo "${{ env.current_version }}"
          match=$(echo ${{ env.current_version }} | grep -E "^(\d+)\.(\d+)\.(\d+)$")
          echo "match"

            




