name: Increment semantic version
on:
  pull_request:
    types:
      - closed  
jobs:
  increment-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get Current Version
        run: echo "CURRENT_VERSION=$(git describe --tags --abbrev=0)" >> "$GITHUB_ENV"
      
      - name: Increment Version
        id: increment-version
        uses: JesseBroxterman/semantic-version-increment@v1
        with:
          current_version: $CURRENT_VERSION
          pr_labels: github.event.pull_request.labels.*.name
          
      - name: Check Output
        run: echo "${{ steps.increment-version.new_version }}"

            
            




