name: Increment semantic version
on:
  pull_request:
    types:
      - closed  
jobs:
  increment-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get current version 
        run: echo "CURRENT_VERSION=$(git describe --tags --abbrev=0)" >> "$GITHUB_ENV"
      
      - name: Parse version
        uses: actions/github-script@v5
        with:
          script: |
            const current_version= process.env.CURRENT_VERSION;
            
            // Regular expression to extract major, minor, and patch components
            const versionRegex = /^(\d+)\.(\d+)\.(\d+)$/;

            const [, major, minor, patch] = current_version.match(versionRegex);

            console.log(`major=${major}`);
            console.log(`minor=${minor}`);
            console.log(`patch=${patch}`);

            process.env['MAJOR'] = major;
            process.env['MINOR'] = minor;
            process.env['PATCH'] = patch;          

      - name: Bump patch
        if: contains(github.event.pull_request.labels.*.name, 'bug')
        run: |
          new_patch=$(($PATCH + 1))
          echo "PATCH=$new_patch" >> "$GITHUB_ENV"
          
      - name: Bump minor
        if: contains(github.event.pull_request.labels.*.name, 'enhancement')
        run: |
          new_minor=$(($MINOR + 1))
          new_patch=0
          echo "MINOR=$new_minor" >> "$GITHUB_ENV"
          echo "PATCH=$new_patch" >> "$GITHUB_ENV"
          
      - name: Assign new version tag
        run: |
          echo "$MAJOR"
          echo "$MINOR"   
          echo "$PATCH"      
   

            
            




